language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_deps"
- "./travis-tool.sh install_r knitr microbenchmark"
- "./travis-tool.sh install_github robertzk/testthatsomemore"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: gwYpXTIahHhzP/qfXOU6Essqzu5pTzAiFp4KJenw1msCxXdtp2r/kdj8aUDlaHADFp3l6p5U9gOGZwZmYNDvgjORXIffQJRn3cCsbJoI4D46lSlJin5/2l98ZTdsru4WS4RvDBJvt7BkAY9f9mHdxSHZWNiHoJW2/gB9lym8QDw=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
